menu:
  Appetizers:
    image: /photos/springrolls.png
    spring rolls:
      description: Grilled pork, shrimp, lettuce, and rice noodle wrapped in rice paper. 
        Served with peanut sauce
      price: 6.95
      image: /photos/springrolls.png
    Vegie Spring Rolls:
      description: Tofu, lettuce and rice noodle wrapped in rice paper. Served with creamy 
        peanut sauce
      price: 6.70
      image: /photos/blank.png
    egg rolls:
      description: three crispy egg rolls filled with chicken, vegetables, and glass noodles.
      price: 8.25
      image: /photos/eggrolls.png
    chicken wings:
      description: Six pieces of chicken wings tossed in our sweet chili sauce.
      price: 10.50
      image: /photos/wings.png
    Fried Calamary:
      description: Crispy calamary sticks served with sweet and sour dipping sauce.
      price: 7.95
      image: /photos/calamari.png
    Banh Xeo:
      description: Stir-fried shrimp, pork, bean sprouts, and onion in a crispy rice flour crepe. Served
        with our signature fish sauce
      price: 9.95
      image: /photos/banhxeo.png
    Green beans:
      description: Stir-fried green beans with garlic and soy sauce
      price: 7.95
      image: /photos/blank.png
    Papaya Salad:
      description: Shredded green papaya, carrot, basil, mint, and peanuts in a spicy lime dressing.
        Served with shrimp flavored crackers
      price: 7.85
      image: /photos/goidudu.png
    Spicy Beef Salad:
      description: Grilled beef, cucumber, tomato, onion, and mint in a spicy lime dressing.
      price: 7.85
      image: /photos/beefsalad.png
    Pork Short Ribs:
      description: marinated pork short ribs tossed in a tamarind basil glaze
      price: 7.85
      image: /photos/suonnon.png
    chicken Pot Stickers:
      description: six pieces of chicken pot stickers served with house soy sauce
      price: 7.85
      image: /photos/potstickers.png
    Cream Cheese Crab Puffs:
      description: six pieces of crispy cream cheese crab puffs
      price: 7.85
      image: /photos/blank.png
    Spicy Adamame:
      description: Adamame tossed in a spicy garlic sauce
      price: 4.5
      image: /photos/adamame.png
  Vermicelli:
    image: /photos/bunthitnuong.png
    Hanoi Rice Vermicelli:
      description: Grilled marinated pork, sausage, and herbs servered with a side of rice vermicelli
      price: 14.5
      image: /photos/blank.png
    Shrimp pork eggroll vermicelli:
      description: Grilled shrimp, pork, and egg roll served over a bed of rice vermicelli and greens.
      price: 13.95
      image: /photos/bunthitnuong.png
    Beef and egg roll vermicelli:
      description: Grilled marinated beef and egg roll served over a bed of rice vermicelli and greens.
      price: 13.95
      image: /photos/blank.png
    Chicken and eggroll vermicelli:
      description: Grilled marinated chicken and egg roll served over a bed of rice vermicelli and greens.
      price: 13.95
      image: /photos/bunga.png
    Lemon-grass beef:
      description: Stir-fried lemongrass beef served over a bed of rice vermicelli and greens.
      price: 13.95
      image: /photos/blank.png
    Tofu Delight:
      description: Stir-fried tofu served over a bed of rice vermicelli and greens.
      price: 13.95
      image: /photos/blank.png
  Rice:
    image: /photos/comtam.png
    Com Tam:
      description: this is a test description
      price: 14.95
      image: /photos/comtam.png
    Pork Chop Country:
      description: Grilled marinated pork chop, slices of cucumber, tomato, and lettuce over broken rice
      price: 14.95
      image: /photos/blank.png
    Grilled Pork and shrim Rice:
      description: Grilled pork and shrimp over rice
      price: 14.95
      image: /photos/comthitnuong.png
    Beef short ribs Rice:
      description: Grilled beef short ribs over rice
      price: 14.95
      image: /photos/blank.png
    Combo Fried Rice:
      description: Fried rice with shrimp, chicken, and beef
      price: 14.95
      image: /photos/blank.png
    Shrimp Fried Rice:
      description: Fried rice with shrimps and vegies
      price: 13.50
      image: /photos/blank.png
    Curry Chicken Rice Plate:
      description: Tender chicken breast, potato and carrot in curry sauce, served with white rice
      price: 13.50
      image: /photos/blank.png
    Veggies Lover:
      description: Mix veggies and tofu stir-fried, served with white rice
      price: 14.50
      image: /photos/blank.png
    Perfect Rice Plate:
      description: Mixed vegies, chicken breast, shrimp, beef stir-fried served with white rice
      price: 14.95
      image: /photos/comtam.png
    Crispy Lemon-grass Chicken:
      description: Crispy Chicken stir-fried with lemongrass, chili and soy served with rice
      price: 14.95
      image: /photos/blank.png
    Mint Chicken:
      description: Minced chicken stir-fried with thai chilies over rice
      price: 14.95
      image: /photos/blank.png
    Vegie Fried Rice:
      description: Fried rice with mixed vegetable and egg
      price: 13.50
      image: /photos/blank.png
    Shaken Beef:
      description: Tender rib eye in cubes sauteed with bell pepper, onion in garlic pepper soy sauce
      price: 18.50
      image: /photos/blank.png
  Pho:
    image: /photos/photai.png
    House Pho:
      description: Our house pho with beef broth, beef slices, beef balls, and beef tripe.
      price: 4.8
      image: /photos/blank.png
    Pho Tai:
      description: Beef slices
      price: 4.5
      image: /photos/photai.png
    Pho Tai Nam:
      description: Beef slices and beef flank
      price: 4.5
      image: /photos/photainam.png
    Pho Bo Vien:
      description: Beef balls
      price: 4.5
      image: /photos/blank.png
    Pho Tai Bo Vien:
      description: Beef slices and beef balls
      price: 4.5
      image: /photos/blank.png
    chicken pho:
      description: Pho with chicken
      price: 4.5
      image: /photos/blank.png
    Veggie Pho:
      description: Pho with tofu and veggies
      price: 4.5
      image: /photos/blank.png
    Seafood Pho:
      description: Pho crab, shrimp and fish ball
      price: 4.5
      image: /photos/phohaisan.png
    Minced crab and shrimp soup:
      description: Minced crab and shrimp soup
      price: 4.5
      image: /photos/bunrieu.png
    Bun Bo Hue:
      description: Thick rice noodle in spicy beef flavored soup with beef and pork
      price: 4.5
      image: /photos/buonbohue.png
    wonton soup:
      description: Wontons made with pork and shrimp, with chicken, and vegetable with egg noddle
      price: 14.50
      image: /photos/wonton.png
    Oxtail Pho:
      description: Tender oxtail meat with rice noodle
      price: 17.25
      image: /photos/blank.png
    Beef Shortrib Pho:
      description: Tender oxtail meat with rice noodle
      price: 18.50
      image: /photos/phosuon.png
  Stir Fries:
    image: /photos/mixaodon.png
    Lat Na:
      description: Thai Style Stir-Fried with chicken breast, shrimps, and rice noodle
      price: 14.95
      image: /photos/blank.png
    Crispy Rice Noodle Cake:
      description: Crispy rice noodle cake with shrimp, chicken, and vegetables
      price: 14.95
      image: /photos/blank.png
    Hong Kong Beef Chow Fun:
      description: Hong Kong styled stir fry beef over rice noodle with soy sauce
      price: 14.95
      image: /photos/blank.png
    Pad Thai:
      description: Thai spicy noodle stir-fried with shrimps, tofu, egg, rice noodle and peanut
      price: 14.95
      image: /photos/blank.png
    Soft Egg Noodle Stir Fry:
      description: Soft egg noodle stir fry with chicken, shrimp, and vegetables
      price: 14.95
      image: /photos/blank.png
    Pan Fried Egg Noodle:
      description: Beef, shrimps, chicken, and veggies over pan fried egg noodle
      price: 14.95
      image: /photos/mixaodon.png
    sweet and sour chicken:
      description: Sweet and sour chicken with pineapple, bell pepper, and onion
      price: 14.25
      image: /photos/sweetandsourchicken.png
    kung pao chicken:
      description: Chicken stir fried with celery, zucchini squash, water chestnut, white onion, bell pepper, and peanut, served with white rice
      price: 14.25
      image: /photos/blank.png
    Mongolian Beef:
      description: Beef, white onion, and green onion, served over crispy fried bean threads and white rice
      price: 14.25
      image: /photos/mongollianbeef.png
    Cashew Chicken:
      description: Chicken Stir-Fried with celecery, Zucchini Squash, water chestnut, white onion, bell pepper and cashew, served with white rice
      price: 14.25
      image: /photos/blank.png
    Chicken or Beef Lo Mein:
      description: Noodle stir fried with cabbage, celery, carrot, white onion and green onion 
      price: 14.25
      image: /photos/blank.png
    Chicken or Beef & Brocoli:
      description: your choice of beef or chicken stir-fried with brocoli 
      price: 14.25
      image: /photos/brocolichicken.png



      



